{% set version = "0.2" %}

package:
  name: jupyterlab_delux
  version: {{ version }}
  
source:
  path: ../

build:
  noarch: python
  number: 0
  entry_points:
    - jupyterlab_delux = jupyterlab_delux:main

requirements:
  build:
    - python
    - pip
    - nodejs
    - jupyterlab =0.32.1
  run:
    - python
    - jupyterlab =0.32.1

    # Python packages corresponding to extensions installed in build.sh
    - ipywidgets >=7.2
    - bqplot >=0.10.5

about:
  home: https://github.com/measejm1/jupyterlab_delux
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A proof-of-concept build of JupyterLab with the ipywidgets and bqplot extensions preinstalled
